src/Entity/Tutos.php
<?php

namespace App\Entity;

use App\Repository\TutosRepository;
use Cocur\Slugify\Slugify;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;
use ApiPlatform\Core\Annotation\ApiResource;

/**
 * @ORM\Entity(repositoryClass=TutosRepository::class)
 * @ORM\Table(
 *     name="tutos",
 *     indexes={
 *          @ORM\Index(columns={"title", "description"}, flags={"fulltext"})
 *     }
 * )
 * @UniqueEntity(
 *     fields={"url"},
 *     message="L'url saisie existe déjà"
 * )
 * @ApiResource(
 *     collectionOperations={},
 *     itemOperations={
 *          "get"={
 *              "controller"=App\Controller\Api\EmptyController::class,
 *              "read"=false,
 *              "deserialize"=false
 *          }
 *      }
 * )
 */
class Tutos
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="tutos")
     * @ORM\JoinColumn(nullable=false)
     */
    private $published_by;

    /**
     * @ORM\Column(type="datetime")
     */
    private $published_at;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotNull()
     * @Assert\Length(min="4", minMessage="Le titre doit faire au moins 8 caractères")
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $creator;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Url(message = "l'url '{{ value }}' n'est pas valide")
     */
    private $url;

    /**
     * @ORM\ManyToMany(targetEntity=Tags::class, cascade={"persist"})
     */
    private $tags;

    /**
     * @ORM\OneToMany(targetEntity=Evaluations::class, mappedBy="tutos")
     */
    private $evaluations;

    /**
     * @ORM\OneToMany(targetEntity=Comments::class, mappedBy="tutos")
     */
    private $comments;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\ManyToOne(targetEntity=Categories::class, inversedBy="tutos")
     */
    private $category;

    /**
     * @ORM\ManyToOne(targetEntity=Langues::class)
     * @ORM\JoinColumn(nullable=false)
     */
    private $langue;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $moy;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $duration;

    /**
     * @ORM\ManyToOne(targetEntity=Prices::class)
     */
    private $price;

    /**
     * @ORM\ManyToOne(targetEntity=Levels::class)
     */
    private $level;

    /**
     * @ORM\ManyToOne(targetEntity=Channels::class, inversedBy="tutos")
     */
    private $channel;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $youtube_id;

    public function __construct()
    {
        $this->tags = new ArrayCollection();
        $this->evaluations = new ArrayCollection();
        $this->comments = new ArrayCollection();

        $this->published_at = new \DateTime();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPublishedBy(): ?User
    {
        return $this->published_by;
    }

    public function setPublishedBy(?User $published_by): self
    {
        $this->published_by = $published_by;

        return $this;
    }

    public function getPublishedAt(): ?\DateTimeInterface
    {
        return $this->published_at;
    }

    public function setPublishedAt(\DateTimeInterface $published_at): self
    {
        $this->published_at = $published_at;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getCreator(): ?string
    {
        return $this->creator;
    }

    public function setCreator(string $creator): self
    {
        $this->creator = $creator;

        return $this;
    }

    public function getSlug()
    {
        return (new Slugify())->slugify($this->getTitle());
    }

    public function getUrl(): ?string
    {
        return $this->url;
    }

    public function setUrl(string $url): self
    {
        $this->url = $url;

        return $this;
    }

    /**
     * @return Collection|Tags[]
     */
    public function getTags(): Collection
    {
        return $this->tags;
    }

    public function addTag(Tags $tag): self
    {
        if (!$this->tags->contains($tag)) {
            $this->tags[] = $tag;
            $tag->addTuto($this);
        }

        return $this;
    }

    public function removeTag(Tags $tag): self
    {
        if ($this->tags->contains($tag)) {
            $this->tags->removeElement($tag);
            $tag->removeTuto($this);
        }

        return $this;
    }

    /**
     * @return Collection|Evaluations[]
     */
    public function getEvaluations(): Collection
    {
        return $this->evaluations;
    }

    /**
     * @return mixed
     */
    public function getMoy()
    {
        return $this->moy;
    }

    /**
     * @param mixed $moy
     * @return Tutos
     */
    public function setMoy($moy)
    {
        $this->moy = $moy;
        return $this;
    }

    public function addEvaluation(Evaluations $evaluation): self
    {
        if (!$this->evaluations->contains($evaluation)) {
            $this->evaluations[] = $evaluation;
            $evaluation->setTutos($this);
        }

        return $this;
    }

    public function removeEvaluation(Evaluations $evaluation): self
    {
        if ($this->evaluations->contains($evaluation)) {
            $this->evaluations->removeElement($evaluation);
            // set the owning side to null (unless already changed)
            if ($evaluation->getTutos() === $this) {
                $evaluation->setTutos(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Comments[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comments $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setTutos($this);
        }

        return $this;
    }

    public function removeComment(Comments $comment): self
    {
        if ($this->comments->contains($comment)) {
            $this->comments->removeElement($comment);
            // set the owning side to null (unless already changed)
            if ($comment->getTutos() === $this) {
                $comment->setTutos(null);
            }
        }

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getCategory(): ?Categories
    {
        return $this->category;
    }

    public function setCategory(?Categories $category): self
    {
        $this->category = $category;

        return $this;
    }

    public function getLangue(): ?Langues
    {
        return $this->langue;
    }

    public function setLangue(?Langues $langue): self
    {
        $this->langue = $langue;

        return $this;
    }

    public function __toString():string
    {
        return $this->title;
    }

    public function getDuration(): ?int
    {
        return $this->duration;
    }

    public function setDuration(?int $duration): self
    {
        $this->duration = $duration;

        return $this;
    }

    public function getPrice(): ?Prices
    {
        return $this->price;
    }

    public function setPrice(?Prices $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getLevel(): ?Levels
    {
        return $this->level;
    }

    public function setLevel(?Levels $level): self
    {
        $this->level = $level;

        return $this;
    }

    public function getChannel(): ?Channels
    {
        return $this->channel;
    }

    public function setChannel(?Channels $channel): self
    {
        $this->channel = $channel;

        return $this;
    }

    public function getYoutubeId(): ?string
    {
        return $this->youtube_id;
    }

    public function setYoutubeId(?string $youtube_id): self
    {
        $this->youtube_id = $youtube_id;

        return $this;
    }
}

src/Form/TutosType.php
<?php

namespace App\Form;

use App\Entity\Categories;
use App\Entity\Channels;
use App\Entity\Langues;
use App\Entity\Levels;
use App\Entity\Prices;
use App\Entity\Tags;
use App\Entity\Tutos;
use Doctrine\ORM\EntityRepository;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\ChoiceList\ChoiceList;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Contracts\Translation\TranslatorInterface;

class TutosType extends AbstractType
{

    protected $translator;

    public function __construct(TranslatorInterface $translator)
    {
        $this->translator = $translator;
    }

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title', null, [
                'label_attr'    => [
                    'class' => 'label'
                ],
                'label' => ucfirst($this->translator->trans('tutos.title.label')) . ' *',
                'attr'  => [
                    'placeholder'   => ucfirst($this->translator->trans('tutos.title.placeholder'))
                ],
                'required'  => true
            ])
            ->add('creator', HiddenType::class, [
                'label_attr'    => [
                    'class' => 'label'
                ],
                'label' => ucfirst($this->translator->trans('tutos.creator.label')),
                'attr'  => [
                    'placeholder'   => ucfirst($this->translator->trans('tutos.creator.placeholder'))
                ],
                'required'  => false
            ])
            ->add('channel', EntityType::class, [
//            ->add('channel', ChannelsType::class, [
                'class'         => Channels::class,
                'label_attr'    => [
                    'class' => 'd-none'
                ],
                'label' => '',
                'required'  => true
            ])
//            ->add('channel', null, [
//                'label_attr'    => [
//                    'class' => 'label'
//                ],
//                'label' => ucfirst($this->translator->trans('tutos.channel.label')),
//                'required'  => false
//            ])
            ->add('url', null, [
                'label_attr'    => [
                    'class' => 'label'
                ],
                'label' => ucfirst($this->translator->trans('tutos.url.label')) . ' *',
                'attr'  => [
                    'placeholder'   => ucfirst($this->translator->trans('tutos.url.placeholder'))
                ],
                'required'  => true
            ])
            ->add('description', TextareaType::class, [
                'label_attr'    => [
                    'class' => 'label'
                ],
                'label'         => ucfirst($this->translator->trans('tutos.description.label')),
                'attr'  => [
                    'class'     => 'mh-250p'
                ],
                'required'      => false
            ])
            ->add('tags', EntityType::class, [
                'class'         => Tags::class,
                'query_builder' => static function (EntityRepository $er) {
                    return $er->createQueryBuilder('t')
                        ->orderBy('t.title', 'ASC');
                },
                'label' => ucfirst($this->translator->trans('tutos.tags.label')) ,
                'choice_value'  => 'id',
                'multiple'      => true,
                'required'      => false,
                'choice_label'  => 'title',
                'expanded'      => true
            ])
            ->add('category', EntityType::class, [
                'class'         => Categories::class,
                'label' => ucfirst($this->translator->trans('tutos.category.label')) . ' *',
                'choice_value'  => 'title',
                'multiple'      => false,
                'required'      => true
            ])
            ->add('langue', EntityType::class, [
                'class'         => Langues::class,
                'label' => ucfirst($this->translator->trans('tutos.langue.label')) . ' *',
                'choice_value'  => 'name',
                'multiple'      => false,
                'required'      => true
            ])
            ->add('price', EntityType::class, [
                'class'         => Prices::class,
                'label'         => ucfirst($this->translator->trans('tutos.price.label')),
                'choice_value'  => 'name',
                'multiple'      => false,
                'required'      => false
            ])
            ->add('level', EntityType::class, [
                'class'         => Levels::class,
                'label'         => ucfirst($this->translator->trans('tutos.level.label')),
                'query_builder' => function(EntityRepository $er) {
                    return $er->createQueryBuilder('l')
                        ->orderBy('l.rank', 'ASC');
                },
                'choice_label'  => 'name',
                'multiple'      => false,
                'required'      => false
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Tutos::class,
        ]);
    }
}

templates/tutos/_light_card.html.twig
<div class="col-lg-4 col-md-12 mb-3">
    <div class="cardbox h-100 shadow-lg bg-white">
        <div class="cardbox-heading">
            <div class="media m-0">
                <div class="media-body">
                    <div class="float-right">
                        <a href="{{ tuto.url }}" target="_blank" class="btn btn-flat btn-flat-icon" title="{{ 'tutos.direct_link'|trans|capitalize }}"><i class="fas fa-external-link-alt"></i></a>
                    </div>
                    <h4 class="m-0 h4">
                        <a href="{{ path('tutos.show', {'slug': tuto.slug, 'id': tuto.id}) }}">{{ tuto.title }}</a>
                    </h4>
                    <p class="m-0">
                        {% if tuto.channel %}
                        <a href="{{ path('channels.show', {'id': tuto.channel.id, 'slug': tuto.channel.slug}) }}" class="" title="{{ 'channel.all_tutos.show'|trans|capitalize }}" data-toggle="tooltip">
                            <i class="fas fa-at"></i> {{ tuto.channel.title }}
                        </a>
                        {% else %}
                            <i class="fas fa-at"></i> {{ tuto.creator }}
                        {% endif %}
                    </p>
                    <span class="float-right text-right"><small>{{ 'tutos.added_at'|trans|capitalize }} {{ tuto.publishedAt|date('d/m/Y') }} {{ 'tutos.added_by'|trans }} {{ tuto.publishedBy }}</small></span>
                </div>
            </div>
        </div>

        <div class="cardbox-item text-center">
            <a href="{{ path('tutos.show', {'slug': tuto.slug, 'id': tuto.id}) }}">
            {% if tuto.url|youtube_thumbnail is not same as ('') %}
                <img src="{{ tuto.url|youtube_thumbnail }}" class="img-fluid" alt="Miniature tutoriel stocké sur youtube - {{ tuto.title }}">
            {% else %}
                <img src="{{ asset('build/images/no-preview-640x480.png') }}" class="img-fluid" alt="Miniature tutoriel non stocké sur youtube - {{ tuto.title }}">
            {% endif %}
            </a>
        </div>

        <div class="cardbox-base p-2">
            <span class="float-right">
                {% if app.user %}
                    {{ shownForTuto(tuto, app.user) }}
                {% endif %}

                <i class="fas fa-comments"></i>
                <em class="mr-2">{{ tuto.comments|length }}</em>

                {{ pinForTuto(tuto, app.user) }}
                <em class="mr-1">{{ countPined(tuto) }}</em>
            </span>
            <div>
            {% if tuto.moy is null %}
                {{ 'tutos.eval.isnull'|trans|capitalize }}
            {% else %}
                <input type="number" id="tutoEvalGlobale" class="star-rating-fix" value="{{ tuto.moy }}" min=0 max=5 step=0.5 data-size="sm">
            {% endif %}
            </div>
        </div>

        <div class="cardbox-comments p-2">
            <span class="badge badge-info badge-pill">{{ tuto.category }}</span>
            <span class="badge badge-info badge-pill">{{ tuto.langue }}</span>

            {% if tuto.price %}
            <span class="badge badge-info badge-pill">{{ tuto.price }}</span>
            {% endif %}
            {% if tuto.level %}
                <span class="badge badge-info badge-pill">{{ tuto.level }}</span>
            {% endif %}

            {% for tag in tuto.tags %}
                <span class="badge badge-primary badge-pill">{{ tag }}</span>
            {% endfor %}
        </div>
    </div>
</div>

templates/tutos/addurl.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ 'tutos.addurl.title'|trans|capitalize }}{% endblock %}

{% block body %}

<section class="mt-2 mb-5">
    <div class="container">
        <h1 class="h1">{{ 'tutos.addurl.title'|trans|capitalize }}</h1>
        <hr class="my-4">
        {{ form_start(form) }}
            {{ form_row(form.url) }}
            <input type="submit" class="btn btn-success" value="{{ 'btn.confirm'|trans }}">
        {{ form_end(form) }}
    </div>

    {% if video is defined %}
    <div class="container mt-3">
        <div class="row">
            <div class="card col-6">
                <img src="{{ channel.thumbnails.default.url }}" class="card-img-top" alt="...">
                <div class="card-body">
                    <h5 class="card-title">{{ video.title }}</h5>
                    <p class="card-text">{{ video.description|nl2br }}</p>
                    <a href="#" class="btn btn-primary">{{ channel.title }}</a>
                </div>
            </div>
        </div>
    </div>
    {% endif %}
</section>

{% endblock %}

templates/tutos/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ 'tutos.show.title'|trans|capitalize }}{% endblock %}

{% block body %}
    <section class="my-2">
        <div class="container">
            <h1 class="h1">
                <span class="h1-text">{{ tuto.title }}</span>

                <span class="float-right small">
                   <a class="text-info align-text-bottom"
                      href="https://twitter.com/intent/tweet?via=tutomarks&text={{ tuto.title|url_encode }}&original_referer={{ url('tutos.show', {'slug': tuto.slug, 'id': tuto.id}) }}&url={{ url('tutos.show', {'slug': tuto.slug, 'id': tuto.id}) }}"
                      target="_blank"
                      data-lang="fr"
                      title="{{ 'btn.twitter.share_title'|trans|capitalize }}"
                   >
                       <i class="fab fa-twitter"></i></a>

                    {% if is_granted('EDIT', tuto) %}
                    <a class="align-text-bottom"
                        href="{{ path('tutos.edit', { 'id' : tuto.id}) }}"
                        title="{{ 'tutos.edit.title'|trans|capitalize }}">
                        <i class="fas fa-edit"></i></a>
                    {% endif %}

                    {% if app.user %}
                    <a href="#" data-toggle="modal" data-target="#js-deadlink" class="align-text-bottom text-danger">
                        <i class="fas fa-unlink" data-toggle="tooltip" title="{{ 'btn.deadlink'|trans|capitalize }}"></i>
                    </a>
                    {% endif %}
                </span>
            </h1>

            <div class="modal fade" id="js-deadlink" tabindex="-1" role="dialog" aria-labelledby="js-deadlink-label" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="js-deadlink-label">{{ 'deadlink.thanks.title'|trans|capitalize }}</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            {{ 'deadlink.thanks.dialog'|trans|capitalize }}
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">{{ 'btn.cancel'|trans|capitalize }}</button>
                            <a href="{{ path('tutos.deadlink', {'id': tuto.id}) }}" class="btn btn-success">{{ 'btn.confirm'|trans|capitalize }}</a>
                        </div>
                    </div>
                </div>
            </div>

            <hr class="my-3">

            {% if tuto.url|youtube_thumbnail is not same as ('') %}
                <div class="row mt-2 mb-3">
                    {{ tuto.url|youtube_player|raw }}
                </div>
            {% endif %}

            <div class="row mt-2 mb-3">
                <div class="col">
                    <div id="channel_card" class="mb-3">
                        {% if tuto.channel %}
                            {% set channel = tuto.channel %}
                            {% set nb = channel.tutos|length %}

                            {% include 'channels/__light_card.html.twig' %}
                        {% else %}
                            <div class="col">
                                <span class="channel_name"><i class="fas fa-at"></i> {{ tuto.creator }}</span><br/>
                            </div>
                        {% endif %}
                    </div>

                    <div class="card mb-3">
                        <div class="card-body">

                            <div class="form-group text-center">
                                <a href="{{ tuto.url }}" target="_blank" class="btn btn-outline-info">{{ 'tutos.url.new_windows'|trans|capitalize }} <i class="fas fa-external-link-alt"></i></a>
                            </div>

                            <div class="form-group">
                                <label class="label">{{ 'tutos.category.label'|trans|capitalize }} :</label>
                                <span class="">{{ tuto.category }}</span>
                            </div>

                            <div class="form-group">
                                <label class="label">{{ 'tutos.langue.label'|trans|capitalize }} :</label>
                                <span class="">{{ tuto.langue }}</span>
                            </div>

                            <div class="form-group">
                                <label class="label">{{ 'tutos.price.label'|trans|capitalize }} :</label>
                                <span class="">{{ tuto.price ?: 'unknown.field'|trans|capitalize }}</span>
                            </div>

                            <div class="form-group">
                                <label class="label">{{ 'tutos.level.label'|trans|capitalize }} :</label>
                                <span class="">{{ tuto.level ?: 'unknown.field'|trans|capitalize }}</span>
                            </div>

                            {% if tuto.tags|length > 0 %}
                                <div class="form-group">
                                    <label class="label">{{ 'tutos.tags.label'|trans|capitalize }} :</label><br/>
                                    {% for tag in tuto.tags %}
                                        <span class="badge badge-primary badge-pill">{{ tag }}</span>
                                    {% endfor %}
                                </div>
                            {% endif %}

                            <div class="form-group">
                                <p class="text-info">{{ 'tutos.published_by.thanks_to'|trans|capitalize }} {{ tuto.publishedBy}} {{ 'tutos.published_by.thanks_for'|trans }} {{ 'tutos.published_at.on'|trans }} {{ tuto.publishedAt|date('d/m/Y') }}</p>
                            </div>

                            <div class="my-4">
                                <div class="row">
                                    <div class="col text-center">
                                        <label for="tutoEvalPersonal">{{ 'tutos.eval.your'|trans|capitalize }}</label><br/>
                                        {% if app.user %}
                                            {% set userNote = evalTuto.getForUser(tuto, app.user) %}
                                            <input type="number" id="tutoEvalPersonal" class="star-rating" value="{{ userNote is null ? '' : userNote }}" min="0" max="5" step=".5" data-size="sm" data-user="{{ app.user.id }}" data-tutos="{{ tuto.id }}" data-url="{{ path('api.eval.tutos') }}">
                                        {% else %}
                                            <a href="{{ path('app_login') }}" class="btn btn-sm btn-outline-info">{{ 'nav.connection'|trans|capitalize }}</a>
                                        {% endif %}
                                    </div>

                                    <div class="col text-center">
                                        {% set note = evalTuto.getTutosMoy(tuto) %}
                                        <label for="tutoEvalGlobale">{{ 'tutos.eval.global'|trans|capitalize }}</label><br/>
                                        <input type="number" id="tutoEvalGlobale" class="star-rating-fix" value="{{ note }}" min=0 max=5 step=0.5 data-size="sm">
                                    </div>
                                </div>
                            </div>

                            {% if app.user %}
                            <div class="my-4">
                                <div class="row">
                                {% set infos = userTutoInformations(app.user, tuto) %}
                                    {% if infos|length is same as 0 %}
                                        <div class="col text-center">
                                            <button class="js-shown btn btn-sm btn-outline-success"
                                               type="button"
                                               data-user="{{ app.user.id }}"
                                               data-value="0"
                                               data-url="{{ path('api.user.tutos.informations') }}"
                                               data-tutos="{{ tuto.id }}">
                                                <i class="far fa-eye"></i><i class="far fa-eye-slash d-none"></i> <span class="js-action-text-shown">{{ 'btn.shown'|trans|capitalize }}</span>
                                            </button>
                                        </div>
                                        <div class="col text-center">
                                            <button class="js-pined btn btn-sm btn-outline-success"
                                               type="button"
                                               data-user="{{ app.user.id }}"
                                               data-value="0"
                                               data-url="{{ path('api.user.tutos.informations') }}"
                                               data-tutos="{{ tuto.id }}">
                                                <i class="fas fa-thumbtack"></i> <span class="js-action-text-pined">{{ 'btn.pined'|trans|capitalize }}</span>
                                            </button>
                                        </div>
                                    {% else %}
                                        <div class="col text-center">
                                            <button class="js-shown btn btn-sm btn-{{ infos.shown ? 'success' : 'outline-success' }}"
                                               type="button"
                                               data-user="{{ app.user.id }}"
                                               data-value="{{ infos.shown }}"
                                               data-url="{{ path('api.user.tutos.informations') }}"
                                               data-tutos="{{ tuto.id }}">
                                                <i class="far fa-eye {{ infos.shown ? 'd-none' }}"></i><i class="far fa-eye-slash {{ infos.shown ? '' : 'd-none' }}"></i> <span class="js-action-text-shown">{{ infos.shown ? 'btn.unshown'|trans|capitalize : 'btn.shown'|trans|capitalize }}</span>
                                            </button>
                                        </div>
                                        <div class="col text-center">
                                            <button class="js-pined btn btn-sm btn-{{ infos.pined ? 'success' : 'outline-success' }}"
                                               type="button"
                                               data-user="{{ app.user.id }}"
                                               data-value="{{ infos.pined }}"
                                               data-url="{{ path('api.user.tutos.informations') }}"
                                               data-tutos="{{ tuto.id }}">
                                                <i class="fas fa-thumbtack"></i> <span class="js-action-text-pined">{{ infos.pined ? 'btn.unpined'|trans|capitalize : 'btn.pined'|trans|capitalize }}</span>
                                            </button>
                                        </div>
                                    {% endif %}
                                </div>
                            </div>
                            {% endif %}
                        </div>
                    </div>
                </div>

                <div class="col">
                    <div class="card">
                        <div class="card-body">
                            <h3 class="h3 card-title">{{ 'tutos.description.label'|trans|capitalize }} :</h3>
                            <hr class="my-2">

                            <p class="card-text">
                                {{ tuto.description|nl2br }}
                            </p>
                        </div>
                    </div>
                </div>
            </div>

            <div class="row mb-4">
                <div class="col text-center">
                    <a href="{{ from is not null ? from : path('home') }}" class="btn btn-outline-info btn-sm">{{ 'back'|trans|capitalize }}</a>
                </div>
            </div>
            
            <tuto-comments data-tuto="{{ tuto.id }}" data-user="{{ app.user ? app.user.id : 0 }}" data-title="{{ 'tutos.comments.single'|trans|capitalize }}"></tuto-comments>
        </div>
    </section>
{% endblock %}