src/Entity/Channels.php
<?php

namespace App\Entity;

use App\Repository\ChannelsRepository;
use Cocur\Slugify\Slugify;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ChannelsRepository::class)
 */
class Channels
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $thumbnails_url;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $site_url;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $youtube_id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $youtube_custom_url;

    /**
     * @ORM\OneToMany(targetEntity=Tutos::class, mappedBy="channel")
     */
    private $tutos;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $twitter;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $github;

    public function __construct()
    {
        $this->tutos = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getThumbnailsUrl(): ?string
    {
        return $this->thumbnails_url;
    }

    public function setThumbnailsUrl(?string $thumbnails_url): self
    {
        $this->thumbnails_url = $thumbnails_url;

        return $this;
    }

    public function getSiteUrl(): ?string
    {
        return $this->site_url;
    }

    public function setSiteUrl(?string $site_url): self
    {
        $this->site_url = $site_url;

        return $this;
    }

    public function getYoutubeId(): ?string
    {
        return $this->youtube_id;
    }

    public function setYoutubeId(?string $youtube_id): self
    {
        $this->youtube_id = $youtube_id;

        return $this;
    }

    public function getYoutubeCustomUrl(): ?string
    {
        return $this->youtube_custom_url;
    }

    public function setYoutubeCustomUrl(?string $youtube_custom_url): self
    {
        $this->youtube_custom_url = $youtube_custom_url;

        return $this;
    }

    /**
     * @return Collection|Tutos[]
     */
    public function getTutos(): Collection
    {
        return $this->tutos;
    }

    public function addTuto(Tutos $tuto): self
    {
        if (!$this->tutos->contains($tuto)) {
            $this->tutos[] = $tuto;
            $tuto->setChannel($this);
        }

        return $this;
    }

    public function removeTuto(Tutos $tuto): self
    {
        if ($this->tutos->removeElement($tuto)) {
            // set the owning side to null (unless already changed)
            if ($tuto->getChannel() === $this) {
                $tuto->setChannel(null);
            }
        }

        return $this;
    }

    public function getSlug(): string
    {
        return (new Slugify())->slugify($this->getTitle());
    }

    public function __toString():string
    {
        return $this->title;
    }

    public function getTwitter(): ?string
    {
        return $this->twitter;
    }

    public function setTwitter(?string $twitter): self
    {
        $this->twitter = $twitter;

        return $this;
    }

    public function getGithub(): ?string
    {
        return $this->github;
    }

    public function setGithub(?string $github): self
    {
        $this->github = $github;

        return $this;
    }
}

src/Form/ChannelsType.php
<?php

namespace App\Form;

use App\Entity\Channels;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\UrlType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Contracts\Translation\TranslatorInterface;

class ChannelsType extends AbstractType
{
    protected $translator;

    public function __construct(TranslatorInterface $translator)
    {
        $this->translator = $translator;
    }

    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('title', null, [
                'label_attr'    => [
                    'class' => 'label'
                ],
                'label' => ucfirst($this->translator->trans('channel.title.label')) . ' *',
                'attr'  => [
                    'placeholder'   => ucfirst($this->translator->trans('channel.title.placeholder'))
                ],
                'required'  => true
            ])
//            ->add('description')
//            ->add('thumbnails_url')
            ->add('site_url', UrlType::class, [
                'label_attr'    => [
                    'class' => 'label'
                ],
                'label' => ucfirst($this->translator->trans('channel.site_url.label')),
                'attr'  => [
                    'placeholder'   => ucfirst($this->translator->trans('channel.site_url.placeholder'))
                ],
                'required'  => false
            ])
            ->add('youtube_id', null, [
                'label_attr'    => [
                    'class' => 'label'
                ],
                'label' => ucfirst($this->translator->trans('channel.youtube_id.label')),
                'attr'  => [
                    'placeholder'   => ucfirst($this->translator->trans('channel.youtube_id.placeholder'))
                ],
                'required'  => false
            ])
//            ->add('youtube_custom_url')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Channels::class,
        ]);
    }
}

src/Controller/ChannelsController.php
<?php

namespace App\Controller;

use App\Entity\Channels;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Contracts\Translation\TranslatorInterface;

class ChannelsController extends AbstractController
{
    private $em;
    private $translator;

    public function __construct(EntityManagerInterface $em, TranslatorInterface $translator)
    {
        $this->em = $em;
        $this->translator = $translator;
    }

    /**
     * @Route("/channels", name="channels")
     */
    public function index(): Response
    {
        return $this->render('channels/index.html.twig', [
            'channels' => $this->em->getRepository(Channels::class)->findAllChannels(),
        ]);
    }


    /**
     * @Route("/{slug}-{id}", name="channels.show", requirements={"slug": "[a-z0-9\-]*"})
     * @param Request $request
     * @param $slug
     * @param $id
     * @return RedirectResponse|Response
     */
    public function show(Request $request, $slug, $id)
    {
        $channel = $this->em->find(Channels::class, $id);
        if(!$channel) {
            $this->addFlash('danger', $this->translator->trans('error.unauthorized'));
            return $this->redirectToRoute('home');
        }

        return $this->render('channels/show.html.twig', [
            'channel'   => $channel,
            'from'      => $request->server->get('HTTP_REFERER')
        ]);
    }
}

templates/channels/__light_card.html.twig
<div class="twPc-div h-100">
    <a class="twPc-bg twPc-block"></a>

    <div>
        <div class="twPc-button">
            {% if nb is same as (0) %}
                <span class="btn btn-info btn-sm">{{ 'channel.no_tutos'|trans|capitalize }}</span>
            {% else %}
                <a href="{{ path('channels.show', {'id': channel.id, 'slug': channel.slug}) }}" class="btn btn-info btn-sm"><i class="fas fa-layer-group"></i> {{ 'channel.all_tutos.link'|trans|capitalize }} [{{ channel.tutos|length }}]</a>
            {% endif %}
        </div>

        <div class="twPc-avatarLink">
            {% if channel.thumbnailsUrl %}
            <img alt="{{ channel.title }}" src="{{ channel.thumbnailsUrl }}" class="twPc-avatarImg">
            {% else %}
            <img alt="{{ channel.title }}" src="{{ asset('build/images/no-preview.png') }}" class="twPc-avatarImg">
            {% endif %}
        </div>

        <div class="twPc-divUser">
            <div class="twPc-divName">
                <i class="fas fa-at"></i> {{ channel.title }}
            </div>
        </div>

        <div class="twPc-divStats">
            <ul class="twPc-Arrange">
                {% if channel.siteUrl %}
                <li class="twPc-ArrangeSizeFit">
                    <a href="{{ channel.siteUrl }}" target="_blank" data-toggle="tooltip" title="{{ 'channel.site_url.link'|trans|capitalize }}">
                        <span class="twPc-StatLabel twPc-block"><i class="fas fa-link"></i></span>
                    </a>
                </li>
                {% endif %}
                {% if channel.youtubeId %}
                <li class="twPc-ArrangeSizeFit">
                    <a href="https://www.youtube.com/channel/{{ channel.youtubeId }}" target="_blank" class="text-danger" data-toggle="tooltip" title="{{ 'channel.youtube.label'|trans|capitalize }}">
                        <span class="twPc-StatLabel twPc-block"><i class="fab fa-youtube"></i></span>
                    </a>
                </li>
                {% endif %}
                {% if channel.twitter %}
                <li class="twPc-ArrangeSizeFit">
                    <a href="{{ channel.twitter }}" target="_blank" class="text-info" data-toggle="tooltip" title="{{ 'channel.twitter.label'|trans }}">
                        <span class="twPc-StatLabel twPc-block"><i class="fab fa-twitter"></i></span>
                    </a>
                </li>
                {% endif %}
                {% if channel.github %}
                <li class="twPc-ArrangeSizeFit">
                    <a href="{{ channel.github }}" target="_blank" data-toggle="tooltip" title="{{ 'channel.github.label'|trans }}">
                        <span class="twPc-StatLabel twPc-block"><i class="fab fa-github"></i></span>
                    </a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</div>

templates/channels/_light_card.html.twig
{% set nb = channel['nb'] %}
{% set channel = channel[0] %}

<div class="col-lg-4 col-md-12 mb-3">
    <div class="cardbox h-100 shadow-lg bg-white">
        <div id="channel_card" class="row">
            {% if channel.thumbnailsUrl %}
                <div class="col-md-3">
                    <img src="{{ channel.thumbnailsUrl }}" class="thumb_channel" alt="">
                </div>
            {% endif%}
            <div class="col">
                <span class="channel_name mb-2"><i class="fas fa-at"></i> {{ channel.title }}</span><br/>

                <div class="list-group list-group-horizontal">
                    {% if channel.siteUrl %}
                        <a href="{{ channel.siteUrl }}" target="_blank" class="list-group-item mb-2 text-secondary" data-toggle="tooltip" title="{{ 'channel.site_url.link'|trans|capitalize }}"><i class="fas fa-link"></i></a>
                    {% endif %}
                    {% if channel.youtubeCustomUrl %}
                        <a href="https://www.youtube.com/c/{{ channel.youtubeCustomUrl }}" target="_blank" class="list-group-item mb-2 text-danger" data-toggle="tooltip" title="{{ 'channel.youtube.label'|trans|capitalize }}"><i class="fab fa-youtube"></i></a>
                    {% endif %}
                    {% if channel.twitter %}
                        <a href="{{ channel.twitter }}" target="_blank" class="list-group-item mb-2 text-info" data-toggle="tooltip" title="{{ 'channel.twitter.label'|trans }}"><i class="fab fa-twitter"></i></a>
                    {% endif %}
                    {% if channel.github %}
                        <a href="{{ channel.github }}" target="_blank" class="list-group-item mb-2" data-toggle="tooltip" title="{{ 'channel.github.label'|trans }}"><i class="fab fa-github"></i></a>
                    {% endif %}
                </div>
                {% if nb is same as (0) %}
                    <span class="mt-2">{{ 'channel.no_tutos'|trans|capitalize }}</span>
                {% else %}
                    <a href="{{ path('channels.show', {'id': channel.id, 'slug': channel.slug}) }}" class="mt-2"><i class="fas fa-layer-group"></i> {{ 'channel.all_tutos.link'|trans|capitalize }} [{{ channel.tutos|length }}]</a>
                {% endif %}
            </div>
        </div>
    </div>
</div>

templates/channels/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ 'channel.all_tutos.show'|trans|capitalize }}{% endblock %}

{% block body %}
    <h2 class="font-weight-light mb-3">{{ 'home.channels'|trans|capitalize }}</h2>
    <hr class="mb-3">

    <div class="row mb-5">
        {% for channel in channels %}
            {% set nb = channel['nb'] %}
            {% set channel = channel[0] %}
            <div class="col-lg-4 col-md-12 mb-3">
                {% include 'channels/__light_card.html.twig' %}
            </div>
        {% endfor %}
    </div>

{% endblock %}

templates/channels/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ 'channel.show.title'|trans|capitalize }}{{ channel.title }}{% endblock %}

{% block body %}
    <section class="my-2">
        <div class="container">
            <h1 class="h1">
                <span class="h1-text">{% if channel.thumbnailsUrl %}<img src="{{ channel.thumbnailsUrl }}" alt="" class="thumb_channel"> {% endif%}{{ channel.title }}</span>
            </h1>

            <hr class="my-3">

            <div class="row mt-2 mb-3">
                <div class="col-mb-1">
                    <div class="list-group mb-3 h-100">
                        {% if channel.siteUrl %}
                            <a href="{{ channel.siteUrl }}" target="_blank" class="list-group-item mb-2 text-secondary" data-toggle="tooltip" title="{{ 'channel.site_url.link'|trans|capitalize }}" data-placement="right"><i class="fas fa-link fa-2x"></i></a>
                        {% endif %}
                        {% if channel.youtubeId %}
                            <a href="https://www.youtube.com/channel/{{ channel.youtubeId }}" target="_blank" class="list-group-item mb-2 text-danger" data-toggle="tooltip" title="{{ 'channel.youtube.label'|trans|capitalize }}" data-placement="right"><i class="fab fa-youtube fa-2x"></i></a>
                        {% endif %}
                        {% if channel.twitter %}
                            <a href="{{ channel.twitter }}" target="_blank" class="list-group-item mb-2 text-info" data-toggle="tooltip" title="{{ 'channel.twitter.label'|trans }}" data-placement="right"><i class="fab fa-twitter fa-2x"></i></a>
                        {% endif %}
                        {% if channel.github %}
                            <a href="{{ channel.github }}" target="_blank" class="list-group-item mb-2" data-toggle="tooltip" title="{{ 'channel.github.label'|trans }}" data-placement="right"><i class="fab fa-github fa-2x"></i></a>
                        {% endif %}
                    </div>
                </div>

                <div class="col">
                    <div class="card">
                        <div class="card-body">
                            <h3 class="h3 card-title">{{ 'channel.description.label'|trans|capitalize }} :</h3>
                            <hr class="my-2">

                            <p class="card-text">
                                {% if channel.description %}
                                    {{ channel.description|nl2br }}
                                {% else %}
                                    -
                                {% endif %}
                            </p>
                        </div>
                    </div>
                </div>
            </div>

            <h2 class="h2 mt-4">
                <span class="h1-text">{{ 'channel.all_tutos.show'|trans|capitalize }}</span>
            </h2>

            <hr class="my-3">

            <div class="row">
                {% for tuto in channel.tutos %}
                    {% include 'tutos/_light_card.html.twig' %}
                {% endfor %}
            </div>

            <div class="row my-4">
                <div class="col text-center">
                    <a href="{{ from is not null ? from : path('home') }}" class="btn btn-outline-info btn-sm">{{ 'back'|trans|capitalize }}</a>
                </div>
            </div>
        </div>
    </section>
{% endblock %}